Support for remote capture from winpcap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -684,6 +684,11 @@ V_INCLS
 V_LIBS
 V_PCAP
 V_FINDALLDEVS
+V_HAVE_REMOTE
+V_REMOTE_FILES
+V_HAVE_TC_API
+V_TC_FILES
+V_TCLIBS
 SSRC
 DYEXT
 DAGLIBS
@@ -1283,6 +1288,8 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-largefile     omit support for large files
   --disable-protochain    disable \"protochain\" insn
+  --disable-remote        disable remote capture capabilities
+  --disable-turbocap        disable support for the turbocap adapters
   --enable-ipv6           build IPv6-capable version [default=yes, if getaddrinfo available]
   --enable-optimizer-dbg  build optimizer debugging code
   --enable-yydebug        build parser debugging code
@@ -3887,11 +3894,13 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <stdio.h>
+#include <sys/types.h> /* for off_t */
+     #include <stdio.h>
 int
 main ()
 {
-return fseeko (stdin, 0, 0) && (fseeko) (stdin, 0, 0);
+int (*fp) (FILE *, off_t, int) = fseeko;
+     return fseeko (stdin, 0, 0) && fp (stdin, 0, 0);
   ;
   return 0;
 }
@@ -3931,11 +3940,13 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #define _LARGEFILE_SOURCE 1
-#include <stdio.h>
+#include <sys/types.h> /* for off_t */
+     #include <stdio.h>
 int
 main ()
 {
-return fseeko (stdin, 0, 0) && (fseeko) (stdin, 0, 0);
+int (*fp) (FILE *, off_t, int) = fseeko;
+     return fseeko (stdin, 0, 0) && fp (stdin, 0, 0);
   ;
   return 0;
 }
@@ -7674,6 +7685,164 @@ fi
 { echo "$as_me:$LINENO: result: $have_socklen_t" >&5
 echo "${ECHO_T}$have_socklen_t" >&6; }
 
+{ echo "$as_me:$LINENO: checking if --enable-remote option is specified" >&5
+echo $ECHO_N "checking if --disable-remote option is specified... $ECHO_C" >&6; }
+# Check whether --disable-remote was given.
+if test "${enable_remote+set}" = set; then
+  enableval=$enable_remote;
+fi
+
+
+case "x$enable_remote" in
+xyes)	enable_remote=enabled	;;
+xno)	enable_remote=disabled	;;
+x)	enable_remote=enabled	;;
+esac
+
+{ echo "$as_me:$LINENO: result: ${enable_remote}" >&5
+echo "${ECHO_T}${enable_remote}" >&6; }
+
+if test "$enable_remote" = "enabled"; then
+
+
+	{ echo "$as_me:$LINENO: checking if remote capture is supported" >&5
+echo $ECHO_N "checking if remote capture is supported... $ECHO_C" >&6; }
+
+	if test -e ./remote-ext.h ; then	# Check that the remote extensions are there
+
+		case "$V_PCAP" in
+
+		linux)
+			V_REMOTE_FILES="pcap-new.c pcap-remote.c sockutils.c"
+			V_HAVE_REMOTE="-DHAVE_REMOTE"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_REMOTE 1
+_ACEOF
+
+			have_remote=yes
+			;;
+
+		bpf)
+		V_REMOTE_FILES="pcap-new.c pcap-remote.c sockutils.c"
+			V_HAVE_REMOTE="-DHAVE_REMOTE"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_REMOTE 1
+_ACEOF
+
+			have_remote=yes
+			;;
+
+		*)
+			have_remote=no
+			;;
+
+		esac
+
+	{ echo "$as_me:$LINENO: result: ${have_remote}" >&5
+echo "${ECHO_T}${have_remote}" >&6; }
+	fi
+
+fi
+
+{ echo "$as_me:$LINENO: checking if --disable-turbocap option is specified" >&5
+echo $ECHO_N "checking if --disable-turbocap option is specified... $ECHO_C" >&6; }
+# Check whether --enable-turbocap was given.
+if test "${enable_turbocap+set}" = set; then
+  enableval=$enable_turbocap;
+fi
+
+
+case "x$enable_turbocap" in
+xyes) enable_turbocap=enabled   ;;
+xno)  enable_turbocap=disabled  ;;
+x)    enable_turbocap=enabled   ;;
+esac
+
+{ echo "$as_me:$LINENO: result: turbocap ${enable_turbocap}" >&5
+echo "${ECHO_T}turbocap ${enable_turbocap}" >&6; }
+
+if test "$enable_turbocap" = "enabled"; then
+
+
+      { echo "$as_me:$LINENO: checking if turbocap is supported" >&5
+echo $ECHO_N "checking if turbocap is supported... $ECHO_C" >&6; }
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+	#include <TcApi.h>;
+
+int
+main ()
+{
+ TC_INSTANCE a; TC_PORT b; TC_BOARD c;
+	TC_INSTANCE i;
+	(void)TcInstanceCreateByName("foo", &i);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  have_turbocap=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	have_turbocap=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+      if test "$have_turbocap" = "yes"; then        # Check that the remote extensions are there
+
+              case "$V_PCAP" in
+
+              linux)
+                      V_TC_FILES="pcap-tc.c"
+                      V_HAVE_TC_API="-DHAVE_TC_API"
+                      V_TCLIBS="-lTcApi -lpthread -lstdc++"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TC_API 1
+_ACEOF
+
+                      have_turbocap=yes
+                      ;;
+
+              *)
+                      have_turbocap=no
+                      ;;
+
+              esac
+      fi
+      { echo "$as_me:$LINENO: result: ${have_turbocap}" >&5
+echo "${ECHO_T}${have_turbocap}" >&6; }
+
+fi
+
 # Check whether --enable-ipv6 was given.
 if test "${enable_ipv6+set}" = set; then
   enableval=$enable_ipv6;
@@ -9180,6 +9349,10 @@ ln -s ${srcdir}/bpf/net net
 
 
 
+# HAVE_REMOTE
+
+
+# END HAVE_REMOTE
 
 
 
@@ -10156,6 +10329,11 @@ V_INCLS!$V_INCLS$ac_delim
 V_LIBS!$V_LIBS$ac_delim
 V_PCAP!$V_PCAP$ac_delim
 V_FINDALLDEVS!$V_FINDALLDEVS$ac_delim
+V_HAVE_REMOTE!$V_HAVE_REMOTE$ac_delim
+V_REMOTE_FILES!$V_REMOTE_FILES$ac_delim
+V_HAVE_TC_API!$V_HAVE_TC_API$ac_delim
+V_TC_FILES!$V_TC_FILES$ac_delim
+V_TCLIBS!$V_TCLIBS$ac_delim
 SSRC!$SSRC$ac_delim
 DYEXT!$DYEXT$ac_delim
 DAGLIBS!$DAGLIBS$ac_delim
@@ -10172,7 +10350,7 @@ INSTALL_DATA!$INSTALL_DATA$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 84; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 89; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
